mt5:
  login: 828304892132539296
  password:HcM7CKdV
  server: "MetaQuotes-Demo"

risk:
  max_risk_per_trade: 0.01
  max_daily_risk: 0.05
  max_open_positions: 3
  stop_loss_pips: 30
  take_profit_pips: 60
  default_lot_size: 0.1
  atr_period: 14
  position_sizing_method: "fixed"

symbols:
  - "EURUSD"
  - "GBPUSD"
bars: 500
monitor:
  alert_threshold: 0.5

database:
  path: "database/trades.db"
